queue_rules:
  - name: default
    merge_conditions:
      - check-success=tests (nixos-24.05)
      - check-success=tests (nixos-unstable)
defaults:
  actions:
    queue:
      merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
