queue_rules:
  - name: default
    merge_conditions:
      - check-success=tests
    batch_size: 5
    merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
