{
  bison,
  buildUBoot,
  fetchurl,
  flex,
  gnutls,
  gzip,
  lib,
  openssl,
  tinyxxd,
}:

buildUBoot {
  pname = "qrb2210-uboot";
  version = "qcom-mainline-2025-12-12";

  src = fetchurl {
    url = "https://github.com/arduino/u-boot/archive/8008ca96a4dc53ddb3e51b96ea7e86d881ab7969.tar.gz";
    hash = "sha256-P6NV2gkcWFaGe3bcnmAvjWfESjDDlJILGh2xA9J5HrE";
  };

  defconfig = "qcom_defconfig";
  extraMeta.platforms = [ "aarch64-linux" ];

  patches = [
    ./patches/0001-qcom-add-extlinux.patch
    ./patches/0002-u-boot-use-extlinux.patch
  ];

  nativeBuildInputs = [
    bison
    flex
    gnutls
    gzip
    openssl
    tinyxxd # `xxd` used when generating defaultenv_autogenerated.h
  ];

  extraMakeFlags = [ "DEVICE_TREE=qcom/qrb2210-arduino-imola" ];

  postInstall = ''
    gzip -n -c u-boot-nodtb.bin > u-boot-nodtb.bin.gz
    cat u-boot-nodtb.bin.gz dts/upstream/src/arm64/qcom/qrb2210-arduino-imola.dtb > u-boot-nodtb.bin.gz-dtb

    install -m 0644 u-boot-nodtb.bin.gz $out/
    install -m 0644 u-boot-nodtb.bin.gz-dtb $out/
  '';

  filesToInstall = [
    "u-boot.bin"
    "u-boot-nodtb.bin"
    "dts/upstream/src/arm64/qcom/qrb2210-arduino-imola.dtb"
  ];
}

