# TAS2783 specific switch control settings

Define.SpeakerMixerElem "tas2783-1 Speaker Playback"

If.twoAmpsStereoToOne {
    Condition {
        Type RegexMatch
        Regex "2"
        String "${var:SpeakerAmps}"
    }
    True {
        Define.SpeakerMixerElem "tas2783 Speaker"
        LibraryConfig.remap.Config {
            ctl.default.map {
                "name='tas2783 Speaker Playback Switch'" {
                    "name='tas2783-1 Speaker Playback Switch'".vindex.0 0
                    "name='tas2783-2 Speaker Playback Switch'".vindex.1 0
                }
                "name='tas2783 Speaker Playback Volume'" {
                    "name='tas2783-1 Speaker Playback Volume'".vindex.0 0
                    "name='tas2783-2 Speaker Playback Volume'".vindex.1 0
                }
            }
        }
    }
}

If.oneAmp {
    Condition {
        Type ControlExists
        Control "name='tas2783-1 Speaker Playback Switch'"
    }
    True.Macro[{ SetLED { LED="speaker" Action="attach" CtlId="tas2783-1 Speaker Playback Switch" } }]
}

If.twoAmps {
    Condition {
        Type ControlExists
        Control "name='tas2783-2 Speaker Playback Switch'"
    }
    True.Macro[{ SetLED { LED="speaker" Action="attach" CtlId="tas2783-2 Speaker Playback Switch" } }]
}
